// Copyright (c) 2026 Hao Li
// SPDX-License-Identifier: BSD-3-Clause

// diameterd is the main Diameter daemon.
// This corresponds to freeDiameterd from the original freeDiameter.
package main

import (
	"flag"
	"fmt"
	"log"
	"net"
	"os"
	"os/signal"
	"syscall"

	"github.com/haoli000/godiam/pkg/core/config"
	"github.com/haoli000/godiam/pkg/core/server"
	"github.com/haoli000/godiam/pkg/proto/dictionary"

	// Import extensions to register them
	_ "github.com/haoli000/godiam/pkg/extensions/app_acct"
	_ "github.com/haoli000/godiam/pkg/extensions/app_cc"
	_ "github.com/haoli000/godiam/pkg/extensions/app_cx"
	_ "github.com/haoli000/godiam/pkg/extensions/app_diameap"
	_ "github.com/haoli000/godiam/pkg/extensions/app_gx"
	_ "github.com/haoli000/godiam/pkg/extensions/app_radgw"
	_ "github.com/haoli000/godiam/pkg/extensions/app_redirect"
	_ "github.com/haoli000/godiam/pkg/extensions/app_s6a"
	_ "github.com/haoli000/godiam/pkg/extensions/app_sip"
	_ "github.com/haoli000/godiam/pkg/extensions/dea_ratelimit"
	_ "github.com/haoli000/godiam/pkg/extensions/dea_route"
	_ "github.com/haoli000/godiam/pkg/extensions/dea_screening"
	_ "github.com/haoli000/godiam/pkg/extensions/dea_topohide"
	_ "github.com/haoli000/godiam/pkg/extensions/rt_busypeers"
	_ "github.com/haoli000/godiam/pkg/extensions/rt_deny_by_size"
	_ "github.com/haoli000/godiam/pkg/extensions/rt_ereg"
	_ "github.com/haoli000/godiam/pkg/extensions/rt_hide_oh"
	_ "github.com/haoli000/godiam/pkg/extensions/rt_ignore_dh"
	_ "github.com/haoli000/godiam/pkg/extensions/rt_load_balance"
	_ "github.com/haoli000/godiam/pkg/extensions/rt_randomize"
	_ "github.com/haoli000/godiam/pkg/extensions/rt_redirect"
	_ "github.com/haoli000/godiam/pkg/extensions/rt_rewrite"
	_ "github.com/haoli000/godiam/pkg/extensions/rt_session_bind"

	_ "github.com/haoli000/godiam/pkg/extensions/dbg_monitor"
	_ "github.com/haoli000/godiam/pkg/extensions/dbg_msg_dumps"
	_ "github.com/haoli000/godiam/pkg/extensions/dbg_msg_timings"
	_ "github.com/haoli000/godiam/pkg/extensions/fifo_stats"
	_ "github.com/haoli000/godiam/pkg/extensions/test_app"

	_ "github.com/haoli000/godiam/pkg/extensions/admin_api"

	_ "github.com/haoli000/godiam/pkg/extensions/prom_metrics"
)

var (
	configFile = flag.String("config", "diameter.yaml", "Path to configuration file")
	genConfig  = flag.Bool("gen-config", false, "Generate example configuration file")
	version    = flag.Bool("version", false, "Show version information")
)

const (
	versionStr = "go-diameter 0.1.0"
)

func main() {
	flag.Parse()

	if *version {
		fmt.Println(versionStr)
		return
	}

	if *genConfig {
		generateExampleConfig()
		return
	}

	// Load configuration
	cfg, err := config.Load(*configFile)
	if err != nil {
		log.Fatalf("Failed to load configuration: %v", err)
	}

	// Initialize dictionary
	dict := dictionary.New()
	if err := dict.LoadBaseProtocol(); err != nil {
		log.Fatalf("Failed to load base protocol: %v", err)
	}
	if err := dict.LoadCreditControl(); err != nil {
		log.Fatalf("Failed to load credit control: %v", err)
	}
	if err := dict.LoadNASREQ(); err != nil {
		log.Fatalf("Failed to load NASREQ: %v", err)
	}
	if err := dict.LoadEAP(); err != nil {
		log.Fatalf("Failed to load EAP: %v", err)
	}
	if err := dict.LoadAll3GPP(); err != nil {
		log.Fatalf("Failed to load 3GPP dictionaries: %v", err)
	}
	if err := dict.LoadSIP(); err != nil {
		log.Fatalf("Failed to load SIP dictionary: %v", err)
	}

	stats := dict.Stats()
	log.Printf("Dictionary loaded: %d vendors, %d applications, %d AVPs, %d commands",
		stats.Vendors, stats.Applications, stats.AVPs, stats.Commands)

	// Create server
	srv := server.New(cfg, dict)

	// Start server
	if err := srv.Start(); err != nil {
		log.Fatalf("Failed to start server: %v", err)
	}

	log.Printf("Diameter daemon started")
	log.Printf("Identity: %s", cfg.Identity)
	log.Printf("Realm: %s", cfg.Realm)
	log.Printf("Listening on port %d", cfg.Listen.Port)

	// Wait for termination signal
	sigChan := make(chan os.Signal, 1)
	signal.Notify(sigChan, syscall.SIGINT, syscall.SIGTERM)
	<-sigChan

	log.Println("Shutting down...")
	srv.Stop()
	log.Println("Shutdown complete")
}

func generateExampleConfig() {
	cfg := config.Example()

	// Get local hostname for identity
	hostname, err := os.Hostname()
	if err == nil {
		cfg.Identity = hostname + ".example.com"
	}

	// Try to get local IP addresses
	addrs, err := net.InterfaceAddrs()
	if err == nil {
		for _, addr := range addrs {
			if ipnet, ok := addr.(*net.IPNet); ok && !ipnet.IP.IsLoopback() {
				if ipnet.IP.To4() != nil {
					cfg.Listen.Addresses = append(cfg.Listen.Addresses, ipnet.IP.String())
					break
				}
			}
		}
	}

	output := `# go-diameter configuration file
# Generated by diameterd --gen-config

# Diameter Identity (must be a valid FQDN)
identity: "` + cfg.Identity + `"

# Diameter Realm
realm: "` + cfg.Realm + `"

# Listen configuration
listen:
  port: 3868
  enable_tcp: true
  enable_sctp: false

# TLS configuration (optional)
tls:
  enabled: false
  # cert_file: "/etc/diameter/cert.pem"
  # key_file: "/etc/diameter/key.pem"
  # ca_file: "/etc/diameter/ca.pem"
  # verify_peer: true
  # min_version: "1.2"

# Local node configuration
local:
  vendor_id: 0
  product_name: "go-diameter"
  firmware_revision: 1
  watchdog_interval: 30s
  connect_timeout: 10s
  request_timeout: 30s

# Peer configuration
peers: []
  # - identity: "peer.example.com"
  #   realm: "example.com"
  #   addresses:
  #     - "192.168.1.100"
  #   port: 3868
  #   tls: false
  #   connect_on_start: true
  #   persistent: true

# Supported applications
applications:
  - id: 4
    type: auth
    # Credit-Control Application
  - id: 3
    type: acct
    # Base Accounting Application
  - id: 5
    type: auth
    # Diameter EAP Application
  - id: 16777216
    type: auth
    # 3GPP Cx Application
  - id: 16777238
    type: auth
    # 3GPP Gx Application
  - id: 16777251
    type: auth
    # 3GPP S6a Application
  - id: 6
    type: auth
    # Diameter SIP Application (RFC 4740)

# Extensions
extensions:
  - name: "dbg_msg_dumps"
  - name: "app_cc"
  - name: "app_acct"
  - name: "app_diameap"
  - name: "app_cx"
  - name: "app_gx"
  - name: "app_s6a"
  - name: "app_sip"
  - name: "rt_rewrite"
    config:
      rules:
        # MAP rules: Copy AVP data from source to destination
        # Example: Map Origin-Host to Destination-Host
        - map:
            source: "Origin-Host"
            destination: "Destination-Host"
        # Example: Map Session-ID from Origin-Realm
        # - map:
        #     source: "Session-ID"
        #     destination: "Proxy-Info:Session-ID"
        # DROP rules: Remove AVPs from messages
        # Example: Drop Vendor-Specific-Application-ID
        # - drop: "Vendor-Specific-Application-ID"
  - name: "dbg_monitor"
    config:
      port: 9000
`

	fmt.Print(output)
}
